market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import AddCartView, ShopCartView

urlpatterns = [
    url(r'^add/$', AddCartView.as_view(), name="添加购物车"),
    url(r'^$', ShopCartView.as_view(), name="购物车页面"),
]

market/apps/goods/urls.py
from django.conf.urls import url

from goods.views import IndexView, CategorView, DetailView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='首页'),
    url(r'^list/(?P<cate_id>\d*)_{1}(?P<order>\d?)\.html$', CategorView.as_view(), name='分类列表'),
    url(r'^detail/(?P<id>\d+)/$', DetailView.as_view(), name='详情'),
]

market/apps/order/urls.py
from django.conf.urls import url

from order.views import ConfirmOrder,  ShowOrder

urlpatterns = [
    url(r'^confirm/$', ConfirmOrder.as_view(), name="确认订单"),
    url(r'^show/$', ShowOrder.as_view(), name="确认支付"),
]

market/apps/user/urls.py
from django.conf.urls import url

from DB.base_view import BaseVerifyView
from user.views import LoginView, RegisterView, index, MemberView, ForgetPassView, PersonalCenterView, SendMsm, \
    ResetPasswordView, saftystep, ResetPhoneView, AddressView, AddressAddView, delAddress, AddressEditView

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name="用户注册"),
    url(r'^login/$', LoginView.as_view(), name="用户登录"),
    url(r'^index/$', index, name="首页"),
    url(r'^member/$', MemberView.as_view(), name="个人中心"),
    url(r'^PersonalCenter/$', PersonalCenterView.as_view(), name="个人资料"),
    url(r'^forgetpassword/$', ForgetPassView.as_view(), name="忘记密码"),
    # url(r'^code/$', user_code, name="验证码"),
    url(r'^SendMsm/$', SendMsm.as_view(), name="验证码"),
    url(r'^resetpassword/$', ResetPasswordView.as_view(), name="重置密码"),
    url(r"^saftystep/$", saftystep, name='安全设置页'),
    url(r"^resetphone/$", ResetPhoneView.as_view(), name='重置手机号码'),
    url(r'^address/$', AddressView.as_view(), name="收货地址首页"),  # 收货地址首页
    url(r'^address/add/$', AddressAddView.as_view(), name="收货地址添加"),  # 收货地址添加
    url(r'^address/edit/(?P<id>\d+)/$', AddressEditView.as_view(), name="收货地址编辑"),  # 收货地址编辑
    url(r'^address/del/$', delAddress, name="收货地址删除"),  # 收货地址删除



]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import IndexView

urlpatterns = [
    # 上传部件自动调用的上传地址,第三方插件
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 添加子路由
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='用户')),  # 用户模块
    url(r'^goods/', include('goods.urls', namespace='goods')),  # 商品模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include("order.urls", namespace="order")),  # 订单模块
    url(r'^$', IndexView.as_view()),
]

market/apps/cart/models.py
from django.db import models

# Create your models here.

market/apps/order/models.py
from django.db import models

from DB.base_model import Base_model


class Transport(Base_model):
    """运算方式"""
    name = models.CharField(max_length=50, verbose_name="运输方式")
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='运费')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "运输方式管理"
        verbose_name_plural = verbose_name


class Order(Base_model):
    """订单基本信息表"""
    order_status_choices = (
        (0, "未支付"),
        (1, "已支付"),
        (2, "已发货"),
        (3, "未评价"),
        (4, "已完成"),
        (5, "退发货"),
        (6, "取消订单"),
    )
    user = models.ForeignKey(to="user.Users", verbose_name="用户")
    order_sn = models.CharField(max_length=64, verbose_name="订单编号")
    goods_total_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="商品总金额")
    transport_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="运费")
    transport = models.CharField(max_length=50, verbose_name="运输方式")
    username = models.CharField(max_length=50, verbose_name="收货人姓名")
    phone = models.CharField(max_length=11, verbose_name="收货人电话号码")
    address = models.CharField(max_length=250, verbose_name="收货人地址")
    order_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="订单总金额")
    order_status = models.SmallIntegerField(choices=order_status_choices, default=0, verbose_name="订单状态")
    payment = models.ForeignKey(to="Payment", null=True, blank=True, verbose_name="支付方式")

    pay_time = models.DateTimeField(verbose_name="支付时间", null=True, blank=True)
    deliver_time = models.DateTimeField(verbose_name="发货时间", null=True, blank=True)
    finish_time = models.DateTimeField(verbose_name="完成时间", null=True, blank=True)

    def __str__(self):
        return self.order_sn

    class Meta:
        verbose_name = "订单管理"
        verbose_name_plural = verbose_name


class OrderGoods(Base_model):
    """订单商品详情表"""
    order = models.ForeignKey(to="Order", verbose_name="订单ID")
    goods_sku = models.ForeignKey(to="goods.GoodsSKU", verbose_name="订单商品ID")
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="商品价格")
    count = models.SmallIntegerField(verbose_name="订单商品数量")

    def __str__(self):
        return "{}:{}".format(self.order.order_sn, self.goods_sku.sku_name)

    class Meta:
        verbose_name = "订单商品管理"
        verbose_name_plural = verbose_name


class Payment(Base_model):
    name = models.CharField(max_length=50, verbose_name="支付方式")
    brief = models.CharField(max_length=200, verbose_name="说明")
    logo = models.ImageField(upload_to="payment/%Y", verbose_name="支付LOGO")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "支付方式管理"
        verbose_name_plural = verbose_name

market/apps/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django_redis import get_redis_connection

from DB.base_view import BaseVerifyView
from goods.models import GoodsSKU
from cart.helper import json_msg, get_cart_count, get_cart_key


class AddCartView(BaseVerifyView):
    def get(self, request):
        pass

    # 操作购物车, 添加购物车数据
    """
        1. 需要接收的参数
            sku_id count 
            从session中获取用户id

        2. 验证参数合法性
            a. 判断 为整数
            b. 要在数据库中存在商品
            c. 验证库存是否充足

        3. 操作数据库
            将购物车 保存到redis
            存储的时候采用的数据库类型为hash
            key           field value  field value
            cart_user_id  sku_id count

    """

    def post(self, request):
        # 1. 接收参数
        user_id = request.session.get("ID")
        sku_id = request.POST.get("sku_id")
        count = request.POST.get("count")

        # a.判断为整数 , 因为数据是二进制的数据要转换
        try:
            sku_id = int(sku_id)
            count = int(count)
        except:
            return JsonResponse(json_msg(1, "参数错误!"))
        # b.要在数据库中存在商品 count必须大于0
        try:
            goods_sku = GoodsSKU.objects.get(pk=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse(json_msg(2, "商品不存在!"))

        # 判断库存
        if goods_sku.stock < count:
            return JsonResponse(json_msg(3, "库存不足!"))

        # 2. 操作数据  购物车加入数量(count),当前商品ID(sku_id)
        # 创建连接
        r = get_redis_connection()
        # 处理购物车的 key
        cart_key = f"cart_{user_id}"

        # 添加
        # 获取购物车中已经存在的数量 加 上 需要添加 与 库存进行比较
        old_count = r.hget(cart_key, sku_id)  # 二进制
        if old_count is None:
            old_count = 0
        else:
            old_count = int(old_count)

        if goods_sku.stock < old_count + count:
            return JsonResponse(json_msg(3, "库存不足!"))

        # 将商品添加到购物车
        # r.hset(cart_key,sku_id,old_count + count)
        # ctrl + shift + u
        r.hincrby(cart_key, sku_id, count)

        # 获取购物车中的总数量
        cart_count = get_cart_count(request)

        # 3. 合成响应
        return JsonResponse(json_msg(0, "添加购物车成功", data=cart_count))


class ShopCartView(BaseVerifyView):
    #   购物车显示页面
    def get(self, request):
        # 获取购物车中的商品信息
        # 1. 接收参数
        user_id = request.session.get("ID")
        # 2. 操作数据库
        r = get_redis_connection()
        # 准备键
        cart_key = get_cart_key(user_id)

        # 从redis获取所有的购物车信息
        cart_datas = r.hgetall(cart_key)
        # 准备一个空列表,保存多个商品
        goods_skus = []
        # 遍历字典
        for sku_id,count in cart_datas.items():
            # 将二进制数据转成整型
            sku_id = int(sku_id)
            count = int(count)

            # 2. 根据购物中的sku_id从 商品sku表中获取商品信息
            try:
                goods_sku = GoodsSKU.objects.get(pk=sku_id, is_delete=False, is_on_sale=True)
            except GoodsSKU.DoesNotExist:
                continue

            # 3. 将购物车中数量和商品信息合成一块儿(给一个已经存在的对象添加属性)
            goods_sku.count = count
            # setattr(goods_sku,'count',count)

            # 保存商品到商品列表
            goods_skus.append(goods_sku)


        # 渲染数据
        context = {
            'goods_skus':goods_skus
        }

        return render(request,'cart/shopcart.html',context=context)

    def post(self, request):
        pass

market/apps/order/views.py
import random
from datetime import datetime

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django_redis import get_redis_connection

from DB.base_view import BaseVerifyView
from cart.helper import get_cart_key, json_msg
from goods.models import GoodsSKU

from order.models import Transport, Order, OrderGoods

from user.models import Users, SpAddress


class ConfirmOrder(BaseVerifyView):
    """确认订单页面"""

    def get(self, request):
        """
            1. 如果没有收货地址显示添加收货地址
               如果有收货地址, 显示默认收货地址, 如果没有默认显示第一个


            2. 展示商品信息
                a. 获取商品sku_ids
                    如何获取多个参数的值 getlist() get()只能获取一个

                b. 根据商品id获取商品信息 并且 获取购物车redis中的数量


        """
        user_id = request.session.get("ID")
        # >>>> 1. 收货地址处理
        address = SpAddress.objects.filter(user_id=user_id).order_by("-isDefault").first()
        # address = None

        # 处理商品信息
        sku_ids = request.GET.getlist("sku_ids")
        # 准备空列表 装商品
        goods_skus = []
        # 准备商品总计
        goods_total_price = 0

        # 准备redis
        r = get_redis_connection()
        # 准备键
        cart_key = get_cart_key(user_id)

        # 遍历
        for sku_id in sku_ids:
            # 商品信息
            try:
                goods_sku = GoodsSKU.objects.get(pk=sku_id)
            except GoodsSKU.DoesNotExist:
                # 商品不存在就回到购物车
                return redirect("cart:购物车展示")

            # 获取对应商品的数量
            try:
                count = r.hget(cart_key, sku_id)
                count = int(count)
            except:
                # 商品不存在就回到购物车
                return redirect("cart:购物车展示")

            # 保存到商品对象上
            goods_sku.count = count

            # 装商品
            goods_skus.append(goods_sku)

            # 统计商品总计
            goods_total_price += goods_sku.price * count

        # 获取运输方式
        transports = Transport.objects.filter(is_delete=False).order_by('price')

        # 渲染数据
        context = {
            'address': address,
            'goods_skus': goods_skus,
            'goods_total_price': goods_total_price,
            'transports': transports,
        }
        return render(request, 'order/tureorder.html', context=context)

    def post(self, request):
        """
            保存订单数据
            1. 订单基本信息表 和 订单商品表
        """
        # 1. 接收参数
        transport_id = request.POST.get('transport')
        sku_ids = request.POST.getlist('sku_ids')
        address_id = request.POST.get('address')

        # 接收用户的id
        user_id = request.session.get("ID")
        user = Users.objects.get(pk=user_id)

        # 验证数据的合法性
        try:
            transport_id = int(transport_id)
            address_id = int(address_id)
            sku_ids = [int(i) for i in sku_ids]
        except:
            return JsonResponse(json_msg(2, "参数错误"))

        # 验证收货地址和运输方式存在
        try:
            address = SpAddress.objects.get(pk=address_id)
        except SpAddress.DoesNotExist:
            return JsonResponse(json_msg(3, "收货地址不存在!"))

        try:
            transport = Transport.objects.get(pk=transport_id)
        except Transport.DoesNotExist:
            return JsonResponse(json_msg(4, "运输方式不存在!"))

        # 2. 操作数据

        # >>>1 . 操作订单基本信息表
        order_sn = "{}{}{}".format(datetime.now().strftime("%Y%m%d%H%M%S"), user_id, random.randrange(10000, 99999))
        address_info = "{}{}{}-{}".format(address.hcity, address.hproper, address.harea, address.detail)
        order = Order.objects.create(
            user=user,
            order_sn=order_sn,
            transport_price=transport.price,
            transport=transport.name,
            username=address.username,
            phone=address.phone,
            address=address_info
        )

        # >>>2. 操作订单商品表
        # 操作redis
        r = get_redis_connection()
        cart_key = get_cart_key(user_id)

        # 准备个变量保存商品总金额
        goods_total_price = 0
        for sku_id in sku_ids:

            # 获取商品对象
            try:
                goods_sku = GoodsSKU.objects.get(pk=sku_id, is_delete=False, is_on_sale=True)
            except GoodsSKU.DoesNotExist:
                return JsonResponse(json_msg(5, "商品不存在"))

            # 获取购物车中商品的数量
            # redis 基于内存的存储,有可能数据会丢失
            try:
                count = r.hget(cart_key, sku_id)
                count = int(count)
            except:
                return JsonResponse(json_msg(6, "购物车中数量不存在!"))

            # 判断库存是否足够
            if goods_sku.stock < count:
                return JsonResponse(json_msg(7, "库存不足!"))

            # 保存订单商品表
            order_goods = OrderGoods.objects.create(
                order=order,
                goods_sku=goods_sku,
                price=goods_sku.price,
                count=count
            )

            # 添加商品总金额
            goods_total_price += goods_sku.price * count

            # 扣除库存, 销量增加
            goods_sku.stock -= count
            goods_sku.sale_num += count
            goods_sku.save()

        # 3. 反过头来操作订单基本信息表 商品总金额 和 订单总金额
        # 订单总金额
        order_price = goods_total_price + transport.price
        order.goods_total_price = goods_total_price
        order.order_price = order_price
        order.save()

        # 4. 清空redis中的购物车数据(对应sku_id)
        r.hdel(cart_key, *sku_ids)

        # 3. 合成响应
        return JsonResponse(json_msg(0, "创建订单成功!", data=order_sn))


class ShowOrder(BaseVerifyView):
    """确认支付页面"""

    def get(self, request):
        # 接收用户id
        user_id = request.session.get("ID")
        # 接收order_sn
        order_sn = request.GET.get("order_sn")

        try:
            order = Order.objects.get(order_sn=order_sn, user_id=user_id)
        except Order.DoesNotExist:
            return redirect("cart:购物车页面")

        # 计算订单总金额
        total = order.order_amount + order.transport_price
        # 渲染订单到页面
        context = {
            "order": order,
            "total": total,
        }
        return render(request, 'order/order.html', context)

    def post(self, request):
        pass

market/templates/cart/shopcart.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}

{% block title %}
    购物车
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">购物车</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
<form method="get" action="{% url 'order:确认订单' %}">
    {% if goods_skus %}

            <ul class="shopcart-list">
                {% for goods_sku in goods_skus %}
                    <li>
                        <label class="am-checkbox am-warning">
                            <input type="checkbox" name="sku_ids" checked="checked" value="{{ goods_sku.pk }}" data-am-ucheck checked>
                        </label>
                        <a href="{% url 'goods:详情' goods_sku.pk %}"><img src="{{ MEDIA_URL }}{{ goods_sku.logo }}" class="shop-pic"/></a>
                        <div class="shop-list-mid">
                            <div class="tit">
                                <a href="{% url 'goods:详情' goods_sku.pk %}">
                                    {{ goods_sku.goods_spu.spu_name }}&emsp;{{ goods_sku.sku_name }}
                                </a>
                            </div>
                            <b class="shop-list-price">￥<i>{{goods_sku.price}}</i></b>
                        </div>
                        <div class="list-cart1">
                            <div class="d-stock">
                                <a class="decrease">-</a>
                                <input id="num" sku_id="{{ goods_sku.pk }}" readonly="" class="text_box sku_count" name="" type="text" value="{{goods_sku.count}}">
                                <a class="increase">+</a>
                            </div>
                        </div>

                    </li>
                {% endfor %}
                <div style="height: 10px; background: #eee;"></div>
            </ul>

    {% endif %}

    <!--购物车空的状态-->
    <div class="login-logo cart_logo" style="{% if goods_skus|length != 0 %}display:none{% endif %}">
        <img src="{% static 'images/care.png' %}">
        <p>亲、您的购物车还是空空的哦，快去装满它!</p>
        <a href="{% url 'goods:首页' %}" class="goshopping">前去逛逛</a>
    </div>



    <div class="shop-fix">

        <label class="am-checkbox am-warning">
            <input id="check_all" type="checkbox" checked="checked" value="" data-am-ucheck checked>
        </label>
        <a class="del">全选</a>
        <input type="button"  class="js-btn" value="去结算">
        <div class="js-text">
            <P>合计：<b>￥<i id="total_price">0.00</i></b></P>
            <p class="js-car">免费配送</p>
        </div>
    </div>
</form>
{% endblock %}

{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:购物车页面' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url '用户:个人中心' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>

{% endblock %}


{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());

                //完成ajax请求
                // 准备数据
                //sku_id 在input 上添加一个自定义属性 sku_id=1
                //找到input获取自定义的属性值
                var sku_id = self.siblings('input').attr('sku_id');
                var data = {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'count': 1,
                    'sku_id': sku_id
                };
                $.ajax({
                    type: "post",
                    url: "{% url 'cart:添加购物车' %}",
                    data: data,
                    dataType: "json",
                    success: function (data) {
                        if (data.code == 0) {
                            //添加成功
                            current_num += 1;
                            self.siblings('input').val(current_num);

                            jisuanTotalPrice();
                        } else if (data.code == 1) {
                            //未登录陆,跳转到登录页面
                            if (confirm("没有登录,是否立即登录?")) {
                                location.href = "{% url '用户:用户登录' %}"
                            }
                        } else {
                            alert(data.errmsg);
                        }
                    }
                });


            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());


                //完成ajax请求
                // 准备数据
                //sku_id 在input 上添加一个自定义属性 sku_id=1
                //找到input获取自定义的属性值
                var sku_id = self.siblings('input').attr('sku_id');
                var data = {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'count': -1,
                    'sku_id': sku_id
                };
                $.ajax({
                    type: "post",
                    url: "{% url 'cart:添加购物车' %}",
                    data: data,
                    dataType: "json",
                    success: function (data) {
                        if (data.code == 0) {
                            //添加成功
                            if (current_num > 1) {
                                current_num -= 1;
                                self.siblings('input').val(current_num);
                            } else {
                                //删除当前li
                                self.closest('li').remove();
                                //判断是否有li
                                if ($(".shopcart-list").find('li').length == 0) {
                                    $(".cart_logo").show();
                                }
                            }
                            jisuanTotalPrice();
                        } else if (data.code == 1) {
                            //未登录陆,跳转到登录页面
                            if (confirm("没有登录,是否立即登录?")) {
                                location.href = "{% url '用户:用户登录' %}"
                            }
                        } else {
                            alert(data.errmsg);
                        }
                    }
                });
            })

            //计算总价格
            function jisuanTotalPrice() {
                //1. 获取所有被选中的复选框 (获取 shopcart-list ul 里面的被选中的复选框  :checked)
                var checkboxes = $('.shopcart-list').find(":checked");
                //2. 获取对应的li
                var total_price = 0;
                $.each(checkboxes, function (i, e) {
                    //i 索引  e元素(复选框)
                    var li = $(e).closest('li');
                    //获取价格
                    var price = $(li).find('.shop-list-price i').text();
                    //获取数量
                    var count = $(li).find(".sku_count").val();
                    total_price += price * count;
                });
                //3. 从li里面查找价格和数量
                //4. 计算总价格
                {#console.debug(total_price);#}
                $("#total_price").text(total_price.toFixed(2));
            }

            //调用
            jisuanTotalPrice();

            //处理全选
            $("#check_all").on("change", function () {
                //获取当前复选框是否被选中的状态 checked 属性的值
                {#console.debug($(this).attr('checked'));#}
                {#console.debug($(this).prop('checked'));#}
                var status = $(this).prop('checked');
                //其他li中复选框与当前复选框状态一致
                $(".shopcart-list").find(":checkbox").prop('checked', status);
                //计算价格
                jisuanTotalPrice();
            });

            //在所有的li中的复选框绑定change时间
            $(".shopcart-list").find(":checkbox").on("change", function () {
                //重新计算价格
                jisuanTotalPrice();
                //判断 选中的复选框 与 所有的复选框的 长度一致 就是全选
                if ($(".shopcart-list").find(":checkbox").length == $(".shopcart-list").find(":checked").length) {
                    $("#check_all").prop('checked', true);
                } else {
                    $("#check_all").prop('checked', false);
                }
            });


            //点击结算按钮,判断必须勾选商品
            $(".js-btn").on("click", function () {
                if ($(".shopcart-list").find(":checked").length == 0) {
                    alert("请选择需要结算的商品!");
                } else {
                    //通过js提交表单 $('form').serialize()
                    $('form').submit();
                }
            })
        })
    </script>

{% endblock %}

market/templates/cart/tureorder.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}
{% block title %}
    确认订单
{% endblock %}
{% block aaa %}
    确认订单
{% endblock %}
{% block content %}
	    <div style="height: 49px;"></div>
	    <div class="add-address">
           <a href="{% url '用户:收货地址添加' %}">+新建收货地址</a>
           <i class="am-icon-angle-right"></i>
        </div>
        <div style="background: #eee; height: 10px;"></div>
        <ul class="shopcart-list" style="padding-bottom: 0;">
	    	<li>
                <img src="{% static 'images/test3.png' %}" class="shop-pic" />
                <div class="order-mid">
                	<div class="tit">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</div>
                	<div class="order-price">￥169 <i>X2</i></div>
                </div>
	    	</li>
	    	<li>
                <img src="{% static 'images/test3.png' %}" class="shop-pic" />
                <div class="order-mid">
                	<div class="tit">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</div>
                	<div class="order-price">￥169 <i>X2</i></div>
                </div>
	    	</li>
	    </ul>
	    <ul class="order-infor">
	    	<li class="order-infor-first">
	    		<span>商品总计：</span>
	    		<i>￥88.00</i>
	    	</li>
	    	<li class="order-infor-first">
	    		<span>运费：</span>
	    		<i>包邮</i>
	    	</li>
	    	<li class="order-infor-first">
	    		<a href="">积分抵费></a>
	    	</li>
	    	<li class="order-infor-first">
	    		<a href="">选择优惠券></a>
	    	</li>
	    </ul>
	    <div style="background: #eee; height: 10px;"></div>
	    <textarea placeholder="备注说明" class="bz-infor"></textarea>
	    <div style="background: #eee; height: 10px;"></div>
	    <div style="height: 55px;"></div>
	    <div class="shop-fix">
	    	<div class="order-text">
	    		应付总额：<span>￥188</span>
	    	</div>
	    	<a href="order.html" class="js-btn">提交订单</a>
	    </div>
{% endblock %}
{% block footer %}
<!--底部-->
<div style="height:55px;"></div>
<div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
    <ul class="am-navbar-nav am-cf am-avg-sm-5">
        <li>
            <a href="{% url 'goods:首页' %}" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
        </li>
        <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
        </li>
        <li>
            <a href="{% url 'cart:购物车页面' %}" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
        </li>
        <li>
            <a href="allorder.html" class="curr">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
        </li>

        <li>
            <a href="{% url '用户:个人中心' %}" class="">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
        </li>
    </ul>
</div>

{% endblock %}