market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import AddCartView, ShopCartView

urlpatterns = [
    url(r'^add/$', AddCartView.as_view(), name="添加购物车"),
    url(r'^$', ShopCartView.as_view(), name="购物车页面"),
]

market/apps/goods/urls.py
from django.conf.urls import url

from goods.views import IndexView, CategorView, DetailView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='首页'),
    url(r'^list/(?P<cate_id>\d*)_{1}(?P<order>\d?)\.html$', CategorView.as_view(), name='分类列表'),
    url(r'^detail/(?P<id>\d+)/$', DetailView.as_view(), name='详情'),
]

market/apps/user/urls.py
from django.conf.urls import url

from DB.base_view import BaseVerifyView
from user.views import LoginView, RegisterView, index, MemberView, ForgetPassView, PersonalCenterView, SendMsm, \
    ResetPasswordView, saftystep, ResetPhoneView, AddressView, AddressAddView, delAddress, AddressEditView

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name="用户注册"),
    url(r'^login/$', LoginView.as_view(), name="用户登录"),
    url(r'^index/$', index, name="首页"),
    url(r'^member/$', MemberView.as_view(), name="个人中心"),
    url(r'^PersonalCenter/$', PersonalCenterView.as_view(), name="个人资料"),
    url(r'^forgetpassword/$', ForgetPassView.as_view(), name="忘记密码"),
    # url(r'^code/$', user_code, name="验证码"),
    url(r'^SendMsm/$', SendMsm.as_view(), name="验证码"),
    url(r'^resetpassword/$', ResetPasswordView.as_view(), name="重置密码"),
    url(r"^saftystep/$", saftystep, name='安全设置页'),
    url(r"^resetphone/$", ResetPhoneView.as_view(), name='重置手机号码'),
    url(r'^address/$', AddressView.as_view(), name="收货地址首页"),  # 收货地址首页
    url(r'^address/add/$', AddressAddView.as_view(), name="收货地址添加"),  # 收货地址添加
    url(r'^address/edit/(?P<id>\d+)/$', AddressEditView.as_view(), name="收货地址编辑"),  # 收货地址编辑
    url(r'^address/del/$', delAddress, name="收货地址删除"),  # 收货地址删除



]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import IndexView

urlpatterns = [
    # 上传部件自动调用的上传地址,第三方插件
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 添加子路由
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='用户')),  # 用户模块
    url(r'^goods/', include('goods.urls', namespace='goods')),  # 商品模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include("order.urls", namespace="order")),  # 订单模块
    url(r'^$', IndexView.as_view()),
]

market/apps/goods/models.py
from django.db import models

# Create your models here.

from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import MinLengthValidator
from django.db import models

# Create your models here.
from DB.base_model import Base_model

is_on_sale_choices = (
    (False, "下架"),
    (True, "上架"),
)


# 商品模型一：
# 商品分类表
# ID
# 分类名
# 分类简介
# 继承基础Base_model模型
class Category(Base_model):
    cate_name = models.CharField(max_length=50,
                                 validators=
                                 [MinLengthValidator(2)],
                                 verbose_name='分类名称')
    brief = models.CharField(max_length=200,
                             null=True,
                             blank=True,
                             verbose_name='描述')
    order = models.SmallIntegerField(default=0, verbose_name="排序")

    def __str__(self):
        return self.cate_name

    class Meta:
        db_table = 'Category'
        verbose_name = '商品分类表'  # 备注：此模型在后台django中admin管理名字为：商品总表
        verbose_name_plural = verbose_name  # 复数名


# 商品模型二:
# 商品SPU表
# ID
# 名称
# 详情
# 继承基础Base_model模型
class GoodsSPU(Base_model):
    spu_name = models.CharField(max_length=50,
                                validators=[MinLengthValidator(2)],
                                verbose_name='商品SPU名称')
    # 使用ckeditor为我们提供的字段，不用重新迁移就可以
    content = RichTextUploadingField(
        validators=[MinLengthValidator(2)],
        verbose_name='商品spu详情')

    def __str__(self):
        return self.spu_name

    class Meta:
        db_table = 'GoodsSPU'
        verbose_name = '商品SPU表'  # 备注：此模型在后台django中admin管理名字为：商品总表
        verbose_name_plural = verbose_name  # 复数名


# 商品模型三：
# 商品 SKU 单位表
# ID
# 单位名（斤，箱）
# 继承基础Base_model模型
class Unit(Base_model):
    name = models.CharField(max_length=10,
                            verbose_name='单位名')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Unit'
        verbose_name = '商品单位表'  # 备注：此模型在后台django中admin管理名字为：商品总表
        verbose_name_plural = verbose_name  # 复数名


# 商品模型四：
# 商品SKU表
# ID
# 商品名
# 简介
# 价格
# 单位    UnitModel
# 库存
# 销量
# LOGO地址
# 是否上架
# 商品分类ID    GoodsClassModel
# 商品spu_id     GoodsSPUModel
# 继承基础Base_model模型
class GoodsSKU(Base_model):
    # 商品名
    sku_name = models.CharField(max_length=100,
                                validators=
                                [MinLengthValidator(2)],
                                verbose_name='商品SKU名称')
    # 简介
    brief = models.CharField(max_length=200,
                             null=True,
                             blank=True,
                             verbose_name='商品简介')
    # 价格（最高金额为10万，小数最多4个小数点）
    price = models.DecimalField(max_digits=10,
                                decimal_places=4,
                                verbose_name='价格')
    # 单位 外键
    unit = models.ForeignKey(to='Unit', verbose_name='单位')

    # 库存
    stock = models.IntegerField(verbose_name='库存',
                                default=0
                                )
    # 销量
    sale_num = models.IntegerField(verbose_name='销量',
                                   default=0
                                   )
    # LOGO地址
    # 默认相册中的第一张图片作为封面图片
    logo = models.ImageField(upload_to='goods/%y%m/%d',
                             verbose_name='商品logo')
    # # 是否上架
    # choic = (
    #     (0, '未上架'),
    #     (1, '已上架'),
    # )
    is_on_sale = models.BooleanField(verbose_name="是否上架",
                                     choices=is_on_sale_choices,
                                     default=False)
    # 商品分类ID  外键  Category
    category = models.ForeignKey(to='Category',
                                 verbose_name='商品分类')
    # 商品spu_id   外键  GoodsSPU
    goods_spu = models.ForeignKey(to='GoodsSPU', verbose_name='商品SPU')

    def __str__(self):
        return self.sku_name

    class Meta:
        db_table = 'GoodsSKU'
        verbose_name = '商品SKU表'  # 备注：此模型在后台django中admin管理名字为：商品总表
        verbose_name_plural = verbose_name  # 复数名


# 商品模型五：
# 商品相册表
# ID
# 图片地址
# 商品SKUID    GoodsSKU
# 继承基础Base_model模型
class Gallery(Base_model):
    img_url = models.ImageField(upload_to='goods/%y%m/%d',
                                verbose_name='相册图片地址')
    goods_sku = models.ForeignKey(to='GoodsSKU',
                                  verbose_name='商品SKU')

    class Meta:
        db_table = 'Gallery'
        verbose_name = '商品相册表'  # 备注：此模型在后台django中admin管理名字为：商品总表
        verbose_name_plural = verbose_name  # 复数名

    def __str__(self):
        return "商品相册:{}".format(self.img_url.name)


# 商品首页轮播商品表
# ID
# 名称
# 商品SKUID
# 图片地址
# 排序（order）
# 继承基础Base_model模型
class Banner(Base_model):
    # 名称
    name = models.CharField(verbose_name="轮播活动名",
                            max_length=150,
                            )
    # 商品SKUID     外键
    goods_sku = models.ForeignKey(to='GoodsSKU',
                                  verbose_name='商品SKU')
    # 图片地址
    img_url = models.ImageField(upload_to='banner/%y%m/%d',
                                verbose_name='轮播图片地址')
    # 排序（order）
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )

    class Meta:
        db_table = 'Banner'
        verbose_name = '首页轮播商品表'  # 备注：此模型在后台django中admin管理名字为：商品总表
        verbose_name_plural = verbose_name  # 复数名

    def __str__(self):
        return self.name


# 商品首页活动表
# ID
# 名称
# 图片地址
# url地址
# 继承基础Base_model模型
class Activity(Base_model):
    # 名称
    title = models.CharField(max_length=150,
                             verbose_name='活动名称'
                             )
    # 图片地址
    img_url = models.ImageField(upload_to='activity/%y%m/%d',
                                verbose_name='活动图片地址')
    # url地址
    url_site = models.URLField(verbose_name='活动的url地址', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'Activity'
        verbose_name = '首页活动管理'  # 备注：此模型在后台django中admin管理名字为：商品总表
        verbose_name_plural = verbose_name  # 复数名


# 首页活动专区
# ID
# 名称
# 描述
# 排序
# 是否上架
# 继承基础Base_model模型
class ActivityZone(Base_model):
    # 名称
    title = models.CharField(verbose_name='活动专区名称', max_length=150)
    brief = models.CharField(verbose_name="活动专区的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )
    is_on_sale = models.BooleanField(verbose_name="上否上线",
                                     choices=is_on_sale_choices,
                                     default=0,
                                     )
    goods_sku = models.ManyToManyField(to="GoodsSKU", verbose_name="商品")

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'ActivityZone'
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name


class ActivityZoneGoods(Base_model):
    # 首页活动专区商品列表

    zone = models.ForeignKey(to="ActivityZone", verbose_name="活动专区")
    goods_sku = models.ForeignKey(to="GoodsSKU", verbose_name="商品SKU")

    class Meta:
        db_table = 'ActivityZoneGoods'
        verbose_name = "首页活动专区商品列表"
        verbose_name_plural = verbose_name

market/apps/goods/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.views import View

from goods.models import GoodsSKU, Category, Banner, Activity, ActivityZone
from cart.helper import get_cart_count


class IndexView(View):
    # 商品首页

    def get(self, request):
        # 获取轮播
        banners = Banner.objects.filter(is_delete=False)
        # 获取活动
        acts = Activity.objects.filter(is_delete=False)

        # 获取特色专区
        act_zones = ActivityZone.objects.filter(is_on_sale=True, is_delete=False)

        # 渲染数据
        context = {
            "banners": banners,
            "acts": acts,
            "act_zones": act_zones,
        }
        return render(request, 'goods/index.html', context=context)

    def post(self, request):
        return HttpResponse('OK')


class CategorView(View):
    # 商品分类

    #
    # 1. 页面刚加载的时候 显示的商品只 显示 排序 排第一的分类下的商品
    # 2. 点击哪个分类 就显示 对应分类下的商品
    # 3. 可以按照 销量,价格(降,升),添加时间,综合(pk) 排序 并且 是对应分类下的商品
    #     添加一个参数order:
    #         0: 综合
    #         1: 销量降
    #         2: 价格升
    #         3: 价格降
    #         4: 添加时间降
    #     order_rule = ['pk', '-sale_num', 'price', '-price', '-Create_time']

    def get(self, request, cate_id, order):
        # 查询所有的分类 默认为0
        categorys = Category.objects.filter(is_delete=False).order_by("-order")

        # 取出第一个分类
        # print(categorys[0])
        # print(categorys.first())
        # 如果 cate_id 为空的话, 默认等于 分类的id
        if cate_id == "":
            category = categorys.first()
            cate_id = category.pk
        else:
            # 根据分类id查询对应的分类
            cate_id = int(cate_id)
            category = Category.objects.get(pk=cate_id)

        # 查询对应类下的所有商品
        # print(category.goodssku_set.all())
        goods_skus = GoodsSKU.objects.filter(is_delete=False, category=category)

        # 排序默认为 0 如果输入为空 那么等于 0
        if order == "":
            order = 0

        # 因为传入的排序是字符串类型,要转换为数字类型
        order = int(order)

        # 排序规则列表
        order_rule = ['pk', '-sale_num', 'price', '-price', '-Create_time']
        # 排序通过上面的列表
        goods_skus = goods_skus.order_by(order_rule[order])
        # if order == 0:
        # 当排序等于0 时, 通过id来排序,-->综合
        #     goods_skus = goods_skus.order_by("pk")
        # elif order == 1:
        # 当排序等于1 时, 通过id来排序,-->销量
        #     goods_skus = goods_skus.order_by("-sale_num")
        # elif order == 2:
        # 当排序等于2 时, 通过id来排序,-->价格升序
        #     goods_skus = goods_skus.order_by("price")
        # elif order == 3:
        # 当排序等于0 时, 通过id来排序,-->价格降序
        #     goods_skus = goods_skus.order_by("-price")
        # elif order == 4:
        # 当排序等于0 时, 通过id来排序,-->最新数据的新品
        #     goods_skus = goods_skus.order_by("-create_time")

        # 获取 当前用户 购物车中商品的总数量
        cart_count = get_cart_count(request)

        context = {
            'categorys': categorys,
            'goods_skus': goods_skus,
            'cate_id': cate_id,
            'order': order,
            'cart_count': cart_count,
        }

        return render(request, 'goods/category.html', context=context)


class DetailView(View):
    """商品详情"""

    def get(self, request, id):
        # 获取商品sku的信息
        goods_sku = GoodsSKU.objects.get(pk=id)

        # 渲染页面
        context = {
            'goods_sku': goods_sku,
        }
        return render(request, 'goods/detail.html', context=context)

market/templates/goods/category.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}

{% block title %}
    商品列表
{% endblock %}

{% block head_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }

        .list-price {
            background: url({% if order == 2 %}{% static 'images/order-bot.png' %}{% elif order == 3 %}{% static 'images/order-top.png' %}{% else %}{% static 'images/order.png' %}{% endif %}) no-repeat right center;
            padding-right: 20px;
            font-style: normal;
        }
    </style>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <form action="{% url 'search:haystack_search' %}" method="get">
            <div class="cate-search">
                <input type="text" name="q" value="" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
                <input type="submit" value="" class="cate-btn"/>
            </div>
        </form>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <ul class="list-nav">
        <li {% if order == 0 %}class="current"{% endif %}><a href="{% url 'goods:分类列表' cate_id 0 %}">综合</a></li>
        <li {% if order == 1 %}class="current"{% endif %}><a href="{% url 'goods:分类列表' cate_id 1 %}">销量</a></li>
        <li {% if order == 2 or order == 3 %}class="current"{% endif %}><a id="price"
                                                                           href="{% url 'goods:分类列表' cate_id 2 %}"><i
                class="list-price">价格</i></a></li>
        <li {% if order == 4 %}class="current"{% endif %}><a href="{% url 'goods:分类列表' cate_id 4 %}">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for category in categorys %}
                <li {% if cate_id == category.pk %}class="current"{% endif %}>
                    <a href="{% url 'goods:分类列表' category.pk order %}">{{ category.cate_name }}</a>
                </li>
            {% endfor %}
        </div>
        <div class="list-right">
            <ul class="list-pro">

                {% for goods_sku in goods_skus %}
                    <li>
                        <a href="{% url 'goods:详情' goods_sku.pk %}"><img src="{{ MEDIA_URL }}{{ goods_sku.logo }}"
                                                                         class="list-pic"/></a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit">
                                <a href="{% url 'goods:详情' goods_sku.pk %}">
                                    {{ goods_sku.goods_spu.spu_name }}&emsp;{{ goods_sku.sku_name }}
                                </a>
                            </div>
                            <div class="am-gallery-desc">￥{{ goods_sku.price }}</div>
                            <p>销量：{{ goods_sku.sale_num }}件</p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input sku_id="{{ goods_sku.pk }}" id="num" readonly="" class="text_box" name=""
                                       type="text" value="0">
                                <a class="increase">+</a>
                            </div>
                        </div>
                    </li>
                {% empty %}
                    <li>
                        <a href="{% url 'goods:分类列表' '' '' %}">该分类下商品走丢了~~~~</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <a href="{% url 'cart:购物车页面' %}">
            <div class="fix-bot-cart"><i id="cart_count">{{ cart_count }}</i></div>
        </a>
        <a href="tureorder.html" class="list-js">去结算</a>
        <a href="tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}


{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());

                // 完成AJAX请求
                //准备数据
                // sku_id 在 input 标签上 添加一个自定义属性 sku_id=1 -->sku_id="{{ goods_sku.pk }}"
                //找到input获取自定义的属性值
                // 定义一个 商品的id 变量 var
                var sku_id = self.siblings('input').attr('sku_id');
                // 定义 得到的数据
                var data = {
                    'csrfmiddlewaretoken': '{{ csrf_token }}', // 得到的令牌
                    'count': 1, // 开始显示的默认数字 1
                    'sku_id': sku_id
                };
                $.ajax({
                    type: "post",
                    url: "{% url 'cart:添加购物车' %}",
                    data: data,
                    dataType: "json",
                    success: function (data) {
                        if (data.code == 0) {
                            //添加成功,每次增加1
                            current_num += 1;
                            if (current_num > 0) {
                                self.siblings(".decrease").fadeIn();
                                self.siblings(".text_box").fadeIn();
                            }
                            self.siblings('input').val(current_num);

                            //修改总数量
                            $("#cart_count").text(data.data);
                        } else if (data.code == 1) {
                            //未登录陆,跳转到登录页面
                            if (confirm("没有登录,是否立即登录?")) {
                                location.href = "{% url '用户:用户登录' %}?next={% url 'goods:分类列表' cate_id order %}"
                            }

                        } else {
                            alert(data.errmsg);
                        }
                    }
                });

            });
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    // 完成AJAX请求
                    //准备数据
                    // sku_id 在 input 标签上 添加一个自定义属性 sku_id=1 -->sku_id="{{ goods_sku.pk }}"
                    //找到input获取自定义的属性值
                    var count = -1;
                    var sku_id = self.siblings('input').attr('sku_id');
                    // 定义 得到的数据
                    var data = {
                        'csrfmiddlewaretoken': '{{ csrf_token }}', // 得到的令牌
                        'count': count, // 开始显示的数据减1
                        'sku_id': sku_id
                    };
                    $.ajax({
                        type: "post",
                        url: "{% url 'cart:添加购物车' %}",
                        data: data,
                        dataType: "json",
                        success: function (data) {
                            if (data.code == 0) {
                                //添加成功,每次减少1
                                current_num -= 1;
                                if (current_num < 1) {
                                    self.fadeOut();
                                    self.siblings(".text_box").fadeOut();
                                }
                                self.siblings('input').val(current_num);

                                //修改总数量
                                $("#cart_count").text(data.data);
                            } else if (data.code == 1) {
                                //未登录陆,跳转到登录页面
                                if (confirm("没有登录,是否立即登录?")) {
                                    location.href = "{% url '用户:用户登录' %}?next={% url 'goods:分类列表' cate_id order %}"
                                }

                            } else {
                                alert(data.errmsg);
                            }
                        }

                    });
                }
            });

        });

        $(function () {
            // 修改 标签上的地址值
            {% if order == 2 %}
                $("#price").attr('href', '{% url "goods:分类列表" cate_id 3 %}');
            {% elif order == 3 %}
                $("#price").attr('href', '{% url "goods:分类列表" cate_id 2 %}');
            {% endif %}
        });
    </script>
{% endblock %}

market/templates/goods/detail.html
{% extends 'basetem/basetem_user.html' %}

{% load static %}

{% block title %}
    {{ goods_sku.goods_spu.spu_name }}&emsp;{{ goods_sku.sku_name }}
{% endblock %}

{% block head_css %}
    <script>
        function changeImage() {
            document.getElementById("imgflag").src = "{% static 'images/redherat.png' %}";
        }
    </script>

    <style>
        .am-slider-default .am-control-nav {
            text-align: center;
        }

        .am-slider-default .am-control-nav li a.am-active {
            background: #cb2527;
        }

        .am-slider-default .am-control-nav li a {
            border: 0;
            width: 10px;
            height: 10px;
        }
    </style>
{% endblock %}


{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">商品详情</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for gallery in goods_sku.gallery_set.all %}
            <li><img src="{{ MEDIA_URL }}{{ gallery.img_url }}"/></li>
            {% endfor %}
        </ul>
    </div>
    <div class="detal-info" style="position: relative; width: 100%;">
        <p>{{ goods_sku.goods_spu.spu_name }}&emsp;{{ goods_sku.sku_name }}</p>
        <h2>商城价：<span>￥{{goods_sku.price}}</span></h2>
        <div class="heart">
            <img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()"/>
            <p>收藏</p>
        </div>
    </div>
    <div class="d-amount">
        <h4>数量：</h4>
        <div class="d-stock">
            <a class="decrease">-</a>
            <input id="num" readonly="" class="text_box" name="" type="text" value="1">
            <input id="count" sku_id="{{ goods_sku.pk }}" type="hidden" value="1">
            <a class="increase">+</a>
            <span id="dprice" class="price" style="display:none"> 36</span>
        </div>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <div class="am-tabs detail-list" data-am-tabs>
        <ul class="am-tabs-nav am-nav am-nav-tabs">
            <li class="am-active"><a href="#tab1">商品详情</a></li>
            <li><a href="#tab2">商品评论</a></li>
        </ul>

        <div class="am-tabs-bd">
            <div class="am-tab-panel am-fade am-in am-active detail " id="tab1">
                {{ goods_sku.goods_spu.content|safe }}
            </div>
            <div class="am-tab-panel am-fade detail " id="tab2">
                <ul class="comment-list">
                    <li class="current"><a href="">全部</a></li>
                    <li><a href="">好评（20）</a></li>
                    <li><a href="">中评（5）</a></li>
                    <li><a href="">差评（0）</a></li>
                </ul>
                <ul class="comment-pic">
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style=" height: 55px;"></div>
    <ul class="fix-shopping">
        <li><a href="javascript:;" class="join">加入购物车</a></li>
        <li><a href="tureorder.html" class="imm-buy">立即购买</a></li>
    </ul>
{% endblock %}

{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                self.siblings('input').val(current_num);
            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 1) {
                    current_num -= 1;
                    self.siblings('input').val(current_num);
                }
            })


            //添加数据到购物车
            $(".join").on('click',function () {
                //完成ajax请求
                // 准备数据
                //sku_id 在input 上添加一个自定义属性 sku_id=1
                //找到input获取自定义的属性值
                var sku_id = $("#count").attr('sku_id');
                var count = $("#count").val();
                var data = {
                    'csrfmiddlewaretoken':'{{ csrf_token }}',
                    'count':count,
                    'sku_id':sku_id
                };
                $.ajax({
                    type:"post",
                    url:"{% url 'cart:添加购物车' %}",
                    data:data,
                    dataType:"json",
                    success: function (data) {
                        if (data.code == 0){
                            //添加成功
                            //跳转到购物车展示页面
                            location.href = "{% url 'cart:购物车页面' %}";
                        }else if(data.code == 1){
                            //未登录陆,跳转到登录页面
                            if(confirm("没有登录,是否立即登录?")){
                                location.href = "{% url '用户:用户登录' %}"
                            }
                        }else {
                            alert(data.errmsg);
                        }
                    }
                });

            });
        })
    </script>
{% endblock %}