market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import AddCartView, ShopCartView

urlpatterns = [
    url(r'^add/$', AddCartView.as_view(), name="添加购物车"),
    url(r'^$', ShopCartView.as_view(), name="购物车页面"),
]

market/apps/order/urls.py
from django.conf.urls import url

from order.views import ConfirmOrder,  ShowOrder

urlpatterns = [
    url(r'^confirm/$', ConfirmOrder.as_view(), name="确认订单"),
    url(r'^show/$', ShowOrder.as_view(), name="确认支付"),
]

market/apps/user/urls.py
from django.conf.urls import url

from DB.base_view import BaseVerifyView
from user.views import LoginView, RegisterView, index, MemberView, ForgetPassView, PersonalCenterView, SendMsm, \
    ResetPasswordView, saftystep, ResetPhoneView, AddressView, AddressAddView, delAddress, AddressEditView

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name="用户注册"),
    url(r'^login/$', LoginView.as_view(), name="用户登录"),
    url(r'^index/$', index, name="首页"),
    url(r'^member/$', MemberView.as_view(), name="个人中心"),
    url(r'^PersonalCenter/$', PersonalCenterView.as_view(), name="个人资料"),
    url(r'^forgetpassword/$', ForgetPassView.as_view(), name="忘记密码"),
    # url(r'^code/$', user_code, name="验证码"),
    url(r'^SendMsm/$', SendMsm.as_view(), name="验证码"),
    url(r'^resetpassword/$', ResetPasswordView.as_view(), name="重置密码"),
    url(r"^saftystep/$", saftystep, name='安全设置页'),
    url(r"^resetphone/$", ResetPhoneView.as_view(), name='重置手机号码'),
    url(r'^address/$', AddressView.as_view(), name="收货地址首页"),  # 收货地址首页
    url(r'^address/add/$', AddressAddView.as_view(), name="收货地址添加"),  # 收货地址添加
    url(r'^address/edit/(?P<id>\d+)/$', AddressEditView.as_view(), name="收货地址编辑"),  # 收货地址编辑
    url(r'^address/del/$', delAddress, name="收货地址删除"),  # 收货地址删除



]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import IndexView

urlpatterns = [
    # 上传部件自动调用的上传地址,第三方插件
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 添加子路由
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='用户')),  # 用户模块
    url(r'^goods/', include('goods.urls', namespace='goods')),  # 商品模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include("order.urls", namespace="order")),  # 订单模块
    url(r'^$', IndexView.as_view()),
]

market/apps/order/models.py
from django.db import models

from DB.base_model import Base_model


class Transport(Base_model):
    """运算方式"""
    name = models.CharField(max_length=50, verbose_name="运输方式")
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='运费')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "运输方式管理"
        verbose_name_plural = verbose_name


class Order(Base_model):
    """订单基本信息表"""
    order_status_choices = (
        (0, "未支付"),
        (1, "已支付"),
        (2, "已发货"),
        (3, "未评价"),
        (4, "已完成"),
        (5, "退发货"),
        (6, "取消订单"),
    )
    user = models.ForeignKey(to="user.Users", verbose_name="用户")
    order_sn = models.CharField(max_length=64, verbose_name="订单编号")
    goods_total_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="商品总金额")
    transport_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="运费")
    transport = models.CharField(max_length=50, verbose_name="运输方式")
    username = models.CharField(max_length=50, verbose_name="收货人姓名")
    phone = models.CharField(max_length=11, verbose_name="收货人电话号码")
    address = models.CharField(max_length=250, verbose_name="收货人地址")
    order_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name="订单总金额")
    order_status = models.SmallIntegerField(choices=order_status_choices, default=0, verbose_name="订单状态")
    payment = models.ForeignKey(to="Payment", null=True, blank=True, verbose_name="支付方式")

    pay_time = models.DateTimeField(verbose_name="支付时间", null=True, blank=True)
    deliver_time = models.DateTimeField(verbose_name="发货时间", null=True, blank=True)
    finish_time = models.DateTimeField(verbose_name="完成时间", null=True, blank=True)

    def __str__(self):
        return self.order_sn

    class Meta:
        verbose_name = "订单管理"
        verbose_name_plural = verbose_name


class OrderGoods(Base_model):
    """订单商品详情表"""
    order = models.ForeignKey(to="Order", verbose_name="订单ID")
    goods_sku = models.ForeignKey(to="goods.GoodsSKU", verbose_name="订单商品ID")
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="商品价格")
    count = models.SmallIntegerField(verbose_name="订单商品数量")

    def __str__(self):
        return "{}:{}".format(self.order.order_sn, self.goods_sku.sku_name)

    class Meta:
        verbose_name = "订单商品管理"
        verbose_name_plural = verbose_name


class Payment(Base_model):
    name = models.CharField(max_length=50, verbose_name="支付方式")
    brief = models.CharField(max_length=200, verbose_name="说明")
    logo = models.ImageField(upload_to="payment/%Y", verbose_name="支付LOGO")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "支付方式管理"
        verbose_name_plural = verbose_name

market/apps/order/views.py
import random
from datetime import datetime

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django_redis import get_redis_connection

from DB.base_view import BaseVerifyView
from cart.helper import get_cart_key, json_msg
from goods.models import GoodsSKU

from order.models import Transport, Order, OrderGoods

from user.models import Users, SpAddress


class ConfirmOrder(BaseVerifyView):
    """确认订单页面"""

    def get(self, request):
        """
            1. 如果没有收货地址显示添加收货地址
               如果有收货地址, 显示默认收货地址, 如果没有默认显示第一个


            2. 展示商品信息
                a. 获取商品sku_ids
                    如何获取多个参数的值 getlist() get()只能获取一个

                b. 根据商品id获取商品信息 并且 获取购物车redis中的数量


        """
        user_id = request.session.get("ID")
        # >>>> 1. 收货地址处理
        address = SpAddress.objects.filter(user_id=user_id).order_by("-isDefault").first()
        # address = None

        # 处理商品信息
        sku_ids = request.GET.getlist("sku_ids")
        # 准备空列表 装商品
        goods_skus = []
        # 准备商品总计
        goods_total_price = 0

        # 准备redis
        r = get_redis_connection()
        # 准备键
        cart_key = get_cart_key(user_id)

        # 遍历
        for sku_id in sku_ids:
            # 商品信息
            try:
                goods_sku = GoodsSKU.objects.get(pk=sku_id)
            except GoodsSKU.DoesNotExist:
                # 商品不存在就回到购物车
                return redirect("cart:购物车展示")

            # 获取对应商品的数量
            try:
                count = r.hget(cart_key, sku_id)
                count = int(count)
            except:
                # 商品不存在就回到购物车
                return redirect("cart:购物车展示")

            # 保存到商品对象上
            goods_sku.count = count

            # 装商品
            goods_skus.append(goods_sku)

            # 统计商品总计
            goods_total_price += goods_sku.price * count

        # 获取运输方式
        transports = Transport.objects.filter(is_delete=False).order_by('price')

        # 渲染数据
        context = {
            'address': address,
            'goods_skus': goods_skus,
            'goods_total_price': goods_total_price,
            'transports': transports,
        }
        return render(request, 'order/tureorder.html', context=context)

    def post(self, request):
        """
            保存订单数据
            1. 订单基本信息表 和 订单商品表
        """
        # 1. 接收参数
        transport_id = request.POST.get('transport')
        sku_ids = request.POST.getlist('sku_ids')
        address_id = request.POST.get('address')

        # 接收用户的id
        user_id = request.session.get("ID")
        user = Users.objects.get(pk=user_id)

        # 验证数据的合法性
        try:
            transport_id = int(transport_id)
            address_id = int(address_id)
            sku_ids = [int(i) for i in sku_ids]
        except:
            return JsonResponse(json_msg(2, "参数错误"))

        # 验证收货地址和运输方式存在
        try:
            address = SpAddress.objects.get(pk=address_id)
        except SpAddress.DoesNotExist:
            return JsonResponse(json_msg(3, "收货地址不存在!"))

        try:
            transport = Transport.objects.get(pk=transport_id)
        except Transport.DoesNotExist:
            return JsonResponse(json_msg(4, "运输方式不存在!"))

        # 2. 操作数据

        # >>>1 . 操作订单基本信息表
        order_sn = "{}{}{}".format(datetime.now().strftime("%Y%m%d%H%M%S"), user_id, random.randrange(10000, 99999))
        address_info = "{}{}{}-{}".format(address.hcity, address.hproper, address.harea, address.detail)
        order = Order.objects.create(
            user=user,
            order_sn=order_sn,
            transport_price=transport.price,
            transport=transport.name,
            username=address.username,
            phone=address.phone,
            address=address_info
        )

        # >>>2. 操作订单商品表
        # 操作redis
        r = get_redis_connection()
        cart_key = get_cart_key(user_id)

        # 准备个变量保存商品总金额
        goods_total_price = 0
        for sku_id in sku_ids:

            # 获取商品对象
            try:
                goods_sku = GoodsSKU.objects.get(pk=sku_id, is_delete=False, is_on_sale=True)
            except GoodsSKU.DoesNotExist:
                return JsonResponse(json_msg(5, "商品不存在"))

            # 获取购物车中商品的数量
            # redis 基于内存的存储,有可能数据会丢失
            try:
                count = r.hget(cart_key, sku_id)
                count = int(count)
            except:
                return JsonResponse(json_msg(6, "购物车中数量不存在!"))

            # 判断库存是否足够
            if goods_sku.stock < count:
                return JsonResponse(json_msg(7, "库存不足!"))

            # 保存订单商品表
            order_goods = OrderGoods.objects.create(
                order=order,
                goods_sku=goods_sku,
                price=goods_sku.price,
                count=count
            )

            # 添加商品总金额
            goods_total_price += goods_sku.price * count

            # 扣除库存, 销量增加
            goods_sku.stock -= count
            goods_sku.sale_num += count
            goods_sku.save()

        # 3. 反过头来操作订单基本信息表 商品总金额 和 订单总金额
        # 订单总金额
        order_price = goods_total_price + transport.price
        order.goods_total_price = goods_total_price
        order.order_price = order_price
        order.save()

        # 4. 清空redis中的购物车数据(对应sku_id)
        r.hdel(cart_key, *sku_ids)

        # 3. 合成响应
        return JsonResponse(json_msg(0, "创建订单成功!", data=order_sn))


class ShowOrder(BaseVerifyView):
    """确认支付页面"""

    def get(self, request):
        # 接收用户id
        user_id = request.session.get("ID")
        # 接收order_sn
        order_sn = request.GET.get("order_sn")

        try:
            order = Order.objects.get(order_sn=order_sn, user_id=user_id)
        except Order.DoesNotExist:
            return redirect("cart:购物车页面")

        # 计算订单总金额
        total = order.order_amount + order.transport_price
        # 渲染订单到页面
        context = {
            "order": order,
            "total": total,
        }
        return render(request, 'order/order.html', context)

    def post(self, request):
        pass

market/templates/order/order.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}
{% block title %}
    支付页面
{% endblock %}
{% block aaa %}
    支付页面
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">确认订单</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <h5 class="order-tit">收货人信息</h5>
    <div class="order-name">
        <p class="order-tele">{{ order.username }}&nbsp;&nbsp;&nbsp;{{ order.phone }}</p>
        <p class="order-add">{{ order.address }}</p>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <h5 class="order-tit">确认订单信息</h5>
    <ul class="shopcart-list" style="padding-bottom: 0; margin-top: 0;">
        {% for og in order.ordergoods_set.all %}
            <li>
                <img src="{{ MEDIA_URL }}{{ og.goods_sku.logo }}" class="shop-pic"/>
                <div class="order-mid">
                    <div class="tit">{{ og.goods_sku.goods_spu.spu_name }}{{ og.goods_sku.sku_name }}</div>
                    <div class="order-price">￥{{ og.price }} <i>X{{ og.count }}</i></div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <ul class="order-infor">
        <li class="order-infor-first">
            <span>商品总计：</span>
            <i>￥{{ order.order_amount }}</i>
        </li>
        <li class="order-infor-first">
            <span>运输方式：{{ order.transport }}</span>
            <i>运费：￥{{ order.transport_price }}</i>
        </li>

    </ul>
    <ul class="pay-style">
        <li>
            <img src="{% static 'images/zhi.png' %}" width="50"/>
            <span>
		   	 		<p>支付宝</p>
		   	 		<p class="descript">推荐有支付宝账号的用户使用</p>
		   	 	</span>
            <label class="am-radio-inline">
                <input type="radio" checked="checked" name="radio10" value="1" data-am-ucheck>
            </label>
        </li>
        <li>
            <img src="{% static 'images/wei.png' %}" width="50"/>
            <span>
		   	 		<p>微信支付</p>
		   	 		<p class="descript">推荐安装微信5.0及以上版本的使用</p>
		   	 	</span>
            <label class="am-radio-inline">
                <input type="radio" name="radio10" value="1" data-am-ucheck>
            </label>
        </li>

    </ul>

    <div style="background: #eee; height: 10px;"></div>
    <textarea placeholder="备注说明" class="bz-infor"></textarea>
    <div style="background: #eee; height: 10px;"></div>
    <div style="height: 55px;"></div>
    <div class="shop-fix">
        <div class="order-text">
            应付总额：<span>￥{{ total }}</span>
        </div>
        <a href="pay.html" class="js-btn">确认支付</a>
    </div>
{% endblock %}
<!--底部-->

{% block footer %}
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="index.html" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="shopcart.html" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="member.html" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

market/templates/order/payment.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>超市</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="renderer" content="webkit">
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">
		<link href="css/amazeui.min.css" rel="stylesheet" type="text/css" />
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		<link href="css/check.css" rel="stylesheet" type="text/css" />
	</head>
	<body style="background: #efefef;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">设置支付密码</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="pay-iphone">手机号：150*****529</div>
	    <div class="pay-box">
	    	<input type="text" placeholder="请输入验证码" />
	    	<input type="button" value="获取验证码" class="pay-box-btn" />
	    </div>
	    <div class="pay-iphone">设置支付密码（请输入6位数字）</div>
	    <ul class="payment">
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    </ul>
	    <div class="pay-iphone">确认支付密码（请输入6位数字）</div>
	    <ul class="payment">
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    	<li><input type="text"/></li>
	    </ul>
	    <input type="button" class="login-btn" value="确认">
	</body>
</html>

market/templates/order/tureorder.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}
{% block title %}
    确认订单
{% endblock %}
{% block aaa %}
    确认订单
{% endblock %}
{% block header %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">确认订单</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {% if address is None %}
            <div class="add-address">
                <a href="{% url '用户:收货地址添加' %}">+新建收货地址</a>
                <i class="am-icon-angle-right"></i>
            </div>
        {% else %}
            <h5 class="order-tit">收货人信息</h5>
            <div class="order-name">
                <a href="{% url '用户:收货地址首页' %}">
                    <p class="order-tele">{{ address.username }}&nbsp;&nbsp;&nbsp;{{ address.phone }}</p>
                    <p class="order-add">
                        {{ address.hcity }}{{ address.hproper }}{{ address.harea }} {{ address.brief }}</p>
                </a>
                <i class="am-icon-angle-right"></i>
            </div>
            <input type="hidden" name="address" value="{{ address.pk }}"/>
        {% endif %}
        <div style="background: #eee; height: 10px;"></div>
        <ul class="shopcart-list" style="padding-bottom: 0;">
            {% for goods_sku in goods_skus %}
                <li>
                    <img src="{{ MEDIA_URL }}{{ goods_sku.logo }}" class="shop-pic"/>
                    <div class="order-mid">
                        <div class="tit">{{ goods_sku.goods_spu.spu_name }} {{ goods_sku.sku_name }}</div>
                        <div class="order-price">￥{{ goods_sku.price }} <i>X{{ goods_sku.count }}</i></div>
                    </div>
                    <input type="hidden" name="sku_ids" value="{{ goods_sku.pk }}">
                </li>
            {% endfor %}
        </ul>
        <ul class="order-infor">
            <li class="order-infor-first">
                <span>商品总计：</span>
                <i>￥<span id="goods_price">{{ goods_total_price }}</span></i>
            </li>
            <li class="order-infor-first">
                <span>运输方式：</span>
                <i>
                    <select name="transport" id="transport">
                        {% for transport in transports %}
                            <option value="{{ transport.pk }}" price="{{ transport.price }}">
                                {{ transport.name }}-¥{{ transport.price }}
                            </option>
                        {% endfor %}
                    </select>
                </i>
            </li>
            {#        <li class="order-infor-first">#}
            {#            <a href="">积分抵费></a>#}
            {#        </li>#}
            {#        <li class="order-infor-first">#}
            {#            <a href="">选择优惠券></a>#}
            {#        </li>#}
        </ul>
        <div style="background: #eee; height: 10px;"></div>
        <textarea placeholder="备注说明" class="bz-infor"></textarea>
        <div style="background: #eee; height: 10px;"></div>
        <div style="height: 55px;"></div>
        <div class="shop-fix">
            <div class="order-text">
                应付总额：<span>￥<i id="total_price">0.00</i></span>
            </div>
            <a href="javascript:;" class="js-btn">提交订单</a>
        </div>
    </form>
{% endblock %}

{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="index.html" class="curr">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:购物车页面' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url '用户:个人中心' %}" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block footer_js %}
    <script>
        $(function () {
            //计算应付总金额
            function totalPrice() {
                //获取商品的总金额
                var goods_price = $("#goods_price").text();
                //获取运费
                var transport_price = $("#transport").find(":selected").attr('price');
                //订单总金额
                var total_price = Number(goods_price) + Number(transport_price);
                {#console.debug(total_price);#}
                $("#total_price").text(total_price.toFixed(2));
            }

            //调用
            totalPrice();

            //绑定修改事件
            $("#transport").on("change", function () {
                //重新计算价格
                totalPrice();
            });


            //绑定点击事件,提交订单数据
            $(".js-btn").on("click", function () {
                //准备数据
                var data = $("form").serialize();
                //发送ajax
                $.ajax({
                    type:"post",
                    url:"{% url 'order:确认订单' %}",
                    data:data,
                    dataType:"json",
                    success:function (data) {
                        if(data.code == 0){
                            //跳转到确认支付页面
                            location.href = "{% url 'order:确认支付' %}?order_sn="+data.data;
                        }else {
                            alert(data.errmsg);
                        }
                    }
                });
            })
        });
    </script>
{% endblock %}