market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import AddCartView, ShopCartView

urlpatterns = [
    url(r'^add/$', AddCartView.as_view(), name="添加购物车"),
    url(r'^$', ShopCartView.as_view(), name="购物车页面"),
]

market/apps/user/urls.py
from django.conf.urls import url

from DB.base_view import BaseVerifyView
from user.views import LoginView, RegisterView, index, MemberView, ForgetPassView, PersonalCenterView, SendMsm, \
    ResetPasswordView, saftystep, ResetPhoneView, AddressView, AddressAddView, delAddress, AddressEditView

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name="用户注册"),
    url(r'^login/$', LoginView.as_view(), name="用户登录"),
    url(r'^index/$', index, name="首页"),
    url(r'^member/$', MemberView.as_view(), name="个人中心"),
    url(r'^PersonalCenter/$', PersonalCenterView.as_view(), name="个人资料"),
    url(r'^forgetpassword/$', ForgetPassView.as_view(), name="忘记密码"),
    # url(r'^code/$', user_code, name="验证码"),
    url(r'^SendMsm/$', SendMsm.as_view(), name="验证码"),
    url(r'^resetpassword/$', ResetPasswordView.as_view(), name="重置密码"),
    url(r"^saftystep/$", saftystep, name='安全设置页'),
    url(r"^resetphone/$", ResetPhoneView.as_view(), name='重置手机号码'),
    url(r'^address/$', AddressView.as_view(), name="收货地址首页"),  # 收货地址首页
    url(r'^address/add/$', AddressAddView.as_view(), name="收货地址添加"),  # 收货地址添加
    url(r'^address/edit/(?P<id>\d+)/$', AddressEditView.as_view(), name="收货地址编辑"),  # 收货地址编辑
    url(r'^address/del/$', delAddress, name="收货地址删除"),  # 收货地址删除



]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import IndexView

urlpatterns = [
    # 上传部件自动调用的上传地址,第三方插件
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls', namespace='search')),
    # 添加子路由
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='用户')),  # 用户模块
    url(r'^goods/', include('goods.urls', namespace='goods')),  # 商品模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include("order.urls", namespace="order")),  # 订单模块
    url(r'^$', IndexView.as_view()),
]

market/apps/user/models.py
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models
from DB.base_model import Base_model


# Create your models here
# 用户的模型
class Users(Base_model):
    username = models.CharField(max_length=11,
                                validators=[
                                    MinLengthValidator(11, '手机号至少11位')
                                ],
                                verbose_name='用户名,使用手机号')
    password = models.CharField(max_length=255, verbose_name='密码')
    my_name = models.CharField(max_length=50, blank=True, null=True,
                               validators=[
                                   MinLengthValidator(2, '用户昵称至少2位')
                               ],
                               verbose_name='用户昵称')
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    sex = models.IntegerField(choices=gender_choices, default=1, verbose_name='性别选择,默认男')
    my_birthday = models.DateField(blank=True, null=True, verbose_name='用户生日,默认为空')
    school = models.CharField(max_length=50, blank=True, null=True, verbose_name='学校')
    my_home = models.CharField(max_length=50, blank=True, null=True, verbose_name='用户详细地址位置')
    address = models.CharField(max_length=50, blank=True, null=True, verbose_name='用户的故乡')
    tel = models.CharField(max_length=11, blank=True, null=True, verbose_name='电话号码')
    # 用户头像从setting文件直接找到静态文件的储存路径
    use_img = models.ImageField(upload_to='user_img', default='images/infortx.png', verbose_name='用户头像')

    def __str__(self):
        return self.username

    class Meta:
        db_table = "sp_user"
        verbose_name = "用户管理"
        verbose_name_plural = verbose_name


# 用户地址的模型
class SpAddress(Base_model):
    hcity = models.CharField(max_length=50, null=True, blank=True, verbose_name="省")
    hproper = models.CharField(max_length=50, null=True, blank=True, verbose_name="市")
    harea = models.CharField(max_length=50, verbose_name="区")
    detail = models.CharField(max_length=255, verbose_name="详细地址")
    username = models.CharField(max_length=100, verbose_name="收货人姓名")
    phone = models.CharField(max_length=11,
                             verbose_name="收货人手机号",
                             validators=[
                                 RegexValidator(r'^1[3-9]\d{9}$', "手机号码格式错误"),
                             ],
                             )
    user = models.ForeignKey(to="user.Users", verbose_name="所属用户")
    isDefault = models.BooleanField(default=False, verbose_name="是否为默认地址")

    # def __str__(self):
    #     return self.username

    class Meta:
        db_table = "sp_address"
        verbose_name = "收货地址管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{}:{}".format(self.username, self.phone)

market/apps/user/views.py
import random
import re
import uuid

from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect

from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django_redis import get_redis_connection

from DB.base_view import BaseVerifyView
from market import set_password
from user.forms import RegisterModelForm, LoginModelForm, MemberModelForm, ResetPassWordForm, AddressEditModelForm, \
    AddressModelForm
from user.helps import login, send_sms, check_login

from user.models import Users, SpAddress


# 定义一个注册视图类
class RegisterView(View):  # 注册 直接定义get 和 post
    template_name = 'user/reg.html'

    def get(self, request):
        # 展示登录表单
        return render(request, self.template_name)

    def post(self, request):
        # 完成用户信息的注册
        # 接收参数
        # 渲染提交的数据
        data = request.POST
        # 验证表单参数合法性 用表单来验证
        form = RegisterModelForm(data)
        if form.is_valid():
            # 操作数据库
            cleaned_data = form.cleaned_data
            # 创建一个注册用户
            # 得到清洗过的数据
            # user = Users()
            # user.username = cleaned_data.get('username')
            # user.password = set_password(cleaned_data.get('password'))
            # user.save()
            username = cleaned_data.get('username')
            password = set_password(cleaned_data.get('password'))
            # 将数据保存到数据库
            Users.objects.create(username=username, password=password)
            return redirect('用户:用户登录')
        else:
            # 错误信息提示
            return render(request, self.template_name, context={'form': form})


# 定义一个登录视图类
class LoginView(View):  # 登录 直接定义get 和 post
    # @check_login_view
    def get(self, request):
        return render(request, 'user/login.html')

    # @check_login_view
    def post(self, request):
        # 接收参数
        data = request.POST
        # 验证数据的合法性
        login_form = LoginModelForm(data)
        if login_form.is_valid():
            # 验证成功
            # 数据合法
            # 从session中得到数据
            # 单独创建方法保存session,更新资料
            user = login_form.cleaned_data.get('user')
            # request.session['ID'] = user.pk
            # request.session['username'] = user.username
            login(request, user)

            referer = request.session.get('referer')
            if referer:
                # 跳转回去
                # 删除session
                del request.session['referer']
                return redirect(referer)

            return redirect('用户:个人中心')
        else:
            # 合成响应
            # 进入到登录页面
            return render(request, 'user/login.html', {'form': login_form})

        # @method_decorator(check_login)
        # def dispatch(self, request, *args, **kwargs):
        #     return super().dispatch(request, *args, **kwargs)


def index(request):  # 首页
    return render(request, 'user/index.html')


# 定义个人中心类视图
class MemberView(BaseVerifyView):  # 个人中心视图类
    # @method_decorator(check_login)
    def get(self, request):
        return render(request, 'user/member.html')

    # @method_decorator(check_login)
    def post(self, request):
        pass


# 个人资料视图类
class PersonalCenterView(BaseVerifyView):
    # 个人资料,需要登录后才能访问
    def get(self, request):
        # 读取数据用户id
        user_id = request.session.get('ID')
        # username = 17629287226
        # 获取用户资料
        user = Users.objects.get(pk=user_id)
        # 渲染到页面
        # 用户的请求方式是get形式, 要将用户的个人信息回显到个人信息页面
        context = {
            'user': user
        }
        return render(request, 'user/infor.html', context=context)

    # @method_decorator(check_login)
    def post(self, request):
        # 完成用户信息的更新
        # 接收参数
        # 渲染提交的数据
        data = request.POST
        user_img = request.FILES.get('use_img')
        user_id = request.session.get('ID')
        # 操作数据
        user = Users.objects.get(pk=user_id)
        user.my_name = data.get('my_name')
        user.sex = data.get('sex')
        # user.my_birthday = data.get('my_birthday')
        user.school = data.get('school')
        user.my_home = data.get('my_home')
        user.address = data.get('address')
        if user_img is not None:
            user.use_img = user_img
        user.save()

        # 同时修改session
        login(request, user)

        # 合成响应
        return redirect('用户:个人中心')


# # 上传头像
# @csrf_exempt
# def headimg(request):
#     user = User.objects.get(pk=request.session.get("ID"))
#     user.head = request.FILES['file']
#     user.save()
#     return JsonResponse({"status": "ok", "head": str(user.head)})


# 忘记密码视图类
class ForgetPassView(View):
    def get(self, request):
        return render(request, 'user/forgetpassword.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        # 验证数据的合法性
        login_form = LoginModelForm(data)
        if login_form.is_valid():
            # 验证成功
            # 数据合法
            password = login_form.cleaned_data['password']
            username = login_form.cleaned_data.get('username')
            password = set_password(password)
            # 更新用户密码
            Users.objects.filter(username=username).update(password=password)
            # 操作数据库
            # 返回到登录
            return redirect('用户:忘记密码')
        else:
            # 合成响应
            # 验证不通过,返回注册页面
            # 进入到注册页面
            return render(request, 'user/forgetpassword.html', {'form': login_form})


# 用户验证码初版
# def user_code(request):
#     if request.method == 'POST':
#         sj = request.POST.get('username', '')
#         resj = re.compile('^1[3-9]\d{9}$')
#         re_sj = re.search(resj, sj)
#         if re_sj:
#             codesj = "".join([str(random.randint(0, 9)) for _ in range(4)])
#             # print([str(random.randint(0, 9)) for _ in range(4)])
#             # print(codesj)
#             a = get_redis_connection("default")
#             a.set(sj, codesj)
#             a.expire(sj, 180)
#             __business_id = uuid.uuid1()
#             # 信息
#             params = "{\"code\":\"%s\",\"product\":\" --电商-- \"}" % codesj
#             send_sms(__business_id, sj, "注册验证", "SMS_2245271", params)
#             return JsonResponse({"ok": 1})
#         else:
#             return JsonResponse({'err': 0, "erra": "cw"})
#     else:
#         return JsonResponse({'err': 0, "erra": "请求方式错误"})

# 发送短信验证码

# 发送短信验证码
class SendMsm(View):

    def get(self, request):
        pass

    def post(self, request):
        # 1, 接收参数
        username = request.POST.get('username', '')
        rs = re.search('^1[3-9]\d{9}$', username)
        # 判断参数合法性
        if rs is None:
            return JsonResponse({'error': 1, 'errmsg': '电话号码格式错误!'})
        # 2. 处理数据

        # 模拟,最后接入运营商
        """
            1. 生成随机验证码
            2. 保存验证码 保存到redis中, 存取速度快,并且可以方便的设置有效时间
            3. 接入运营商
        """

        # >>>1. 生成随机验证码字符串
        random_code = "".join([str(random.randint(0, 9)) for _ in range(6)])
        print("---随机验证码为==={}---".format(random_code))

        # >>>2. 保存验证码到redis中
        # 获取连接
        r = get_redis_connection()
        # 保存手机号码对应的验证码
        r.set(username, random_code)
        r.expire(username, 60)  # 设置60秒后过期

        # # 首先获取当前手机号码的发送次数
        # key_times = "{}_times".format(username)
        # now_times = r.get(key_times)  # 从redis获取的二进制,需要转换
        # # print(int(now_times))
        # if now_times is None or int(now_times) < 10:
        #     # 保存手机发送验证码的次数, 不能超过10次
        #     r.incr(key_times)
        #     # 设置一个过期时间
        #     r.expire(key_times, 3600)  # 一个小时后再发送
        # else:
        #     # 返回,告知用户发送次数过多
        #     return JsonResponse({"error": 1, "errmsg": "发送次数过多"})

        # >>>3. 接入运营商
        __business_id = uuid.uuid1()
        params = "{\"code\":\"%s\",\"product\":\" 张森爸爸的小可爱 \"}" % random_code
        # print(params)
        rs = send_sms(__business_id, username, "注册验证", "SMS_2245271", params)
        print(rs.decode('utf-8'))

        # 3. 合成响应
        return JsonResponse({'error': 0})


# 定义一个函数,实现对安全设置选项页的展示
@check_login
def saftystep(request):
    return render(request, 'user/saftystep.html')


# 定义一个类,实现对用户密码的修改
class ResetPasswordView(BaseVerifyView):
    # 用户的请求方式是get形式, 展示添加修改密码的表单
    def get(self, request):
        id = request.session.get('id')
        return render(request, 'user/password.html', {"id": id})

    # 用户的请求方式是post方式时
    def post(self, request):
        # 接收用户传过来的参数
        data = request.POST
        # 创建一个对象来检查信息的合法性
        form = ResetPassWordForm(data)
        # 验证数据的合法性
        if form.is_valid():
            # 数据合法
            # 接收清洗后的数据
            id = request.session.get('id')
            if form.check_password(request):
                # 密码一致,将数据写入到数据库当中
                # 将密码加密
                password1 = set_password(form.cleaned_data.get('password1'))
                # 将密码写到数据库
                Users.objects.filter(pk=id).update(password=password1)
                # 跳转到登录页面
                return redirect('用户:用户登录')
            else:
                return render(request, 'user/password.html', {"form": form})

        else:
            # 数据不合法, 继续修改
            return render(request, 'user/password.html/', {"form": form})


"""
# 密码一致,将数据写入到数据库当中
# 将密码加密
password1 = set_password(form.cleaned_data.get('password1'))
# 将密码写到数据库
Users.objects.filter(pk=id).update(password=password1)
# 跳转到登录页面
return redirect('users:用户登录')
"""  # 利用密码查找密码,没有用id去查找


# 定义一个修改用户手机号码的类
class ResetPhoneView(BaseVerifyView):
    # 用户以GET方式请求时
    def get(self, request):
        return render(request, 'user/boundphone.html')

    # 当用户以post方式请求时
    def post(self, request):
        return HttpResponse("ok")


class AddressView(BaseVerifyView):
    # 收货地址列表页

    def get(self, request):
        # 获取收货地址,所有的, 当前用户的
        user_id = request.session.get("ID")
        # 查询
        addresses = SpAddress.objects.filter(user_id=user_id, is_delete=False).order_by("-isDefault")

market/templates/user/boundphone.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}
{% block title %}
修改手机号码
{% endblock %}
{% block aaa %}
   修改手机号码
{% endblock %}
{% block head_css %}
<link href="{% static 'css/check.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<div class="pay-iphone">请填写新手机号并进行验证</div>
	    <div class="pay-box">
	    	<input type="text" placeholder="请输入新手机号" />
	    	<input type="button" value="获取验证码" class="pay-box-btn" />
	    </div>
	    <input type="text" placeholder="请输入验证码" class="login-password" />
	    <input type="button" class="login-btn" value="确认">
	    <div class="bound-text">
		    <h2>手机绑定规则</h2>
		    <p>1.一个手机号码只可以绑定一个账户；</p>
	        <p>2.如果无法绑定手机，请联系客服协助解决。</p>
        </div>
{% endblock %}

market/templates/user/gladdress.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">管理收货地址</a>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="{% url '用户:收货地址添加' %}" class="">
                <i class="am-icon-plus"></i>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="address-list">
        {% for address in addresses %}
            <li data-id="{{ address.pk }}" {% if address.isDefault %}class="curr"{% endif %}>
                <p>收货人：{{ address.username }}&nbsp;&nbsp;{{ address.phone }}</p>
                <p class="order-add1">收货地址：
                    {{ address.hcity }}
                    {{ address.hproper }}
                    {{ address.harea }}
                    {{ address.detail }}
                </p>
                <hr/>
                <div class="address-cz">
                    <label class="am-radio am-warning">
                        <input type="radio" name="radio3" data-am-ucheck {% if address.isDefault %}
                               checked
                        {% endif %}> 设为默认
                    </label>
                    <a href="{% url '用户:收货地址编辑' address.pk %}"><img src="{% static 'images/bj.png' %}" width="18"/>编辑</a>
                    <a href="javascript:;" class="del">删除</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}


{% block footer_js %}
<script>
    $(function () {
        //绑定删除
        $(".del").on("click",function () {
            //ajax发起删除
            //准备数据
            var li = $(this).parents("li");
            var id = li.attr("data-id");
            //发送ajax
            $.ajax({
                type:"post",
                url:"{% url '用户:收货地址删除' %}",
                data:{
                    "id":id,
                    "csrfmiddlewaretoken":"{{ csrf_token }}"
                },
                dataType:"json",
                success:function (data) {
                    if(data.code == 0){
                        li.remove();
                    }else {
                        alert("删除失败!");
                    }
                }
            })
        })
    })
</script>
{% endblock %}

market/templates/user/login.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}
{% block title %}
    登录
{% endblock %}
{% block aaa %}
    登录
{% endblock %}
{% block content %}
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        <div style="height: 49px;"></div>
        <!--<div class="login-logo">
            <img src="images/logo.png" />
        </div>-->
        <div style="height: 3rem;"></div>
        <input type="text" name="username" id="mobile" placeholder="请输入用户名/手机号" value="{{ request.POST.username }}" class="login-name">
        <p class="am-text-danger">{{ form.errors.username.0 }}</p>

        <p class="am-text-danger">{{ context }}</p>
        <input type="password" name="password" id="password" placeholder="请输入密码" value="{{ request.POST.password }}" class="login-password">
        <p class="am-text-danger">{{ form.errors.password.0 }}</p>
        <p class="am-text-danger">{{ context }}</p>
        <input type="submit" class="login-btn" value="我要登录">
        <div class="agree">
            <a href="{% url '用户:用户注册' %}">免费注册</a>
            <a href="{% url '用户:忘记密码' %}" class="forget">忘记密码？</a>
        </div>
    </form>
    <div class="line"></div>
    <div class="line-text">第三方账号登录</div>
    <ul class="second-login">
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
    </ul>

{% endblock %}

market/templates/user/member.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}

{% block title %}
    个人中心
{% endblock %}
{% block aaa %}
    个人中心
{% endblock %}
{% block content %}
    <body style="background: #f6f6f6;">
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <h1 class="am-header-title">
            <a href="" class="">个人中心</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <div class="member">
        <div class="mem-tit">{{ request.session.username }}
            <a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
        </div>
        <div class="mem-pic">
            <div class="mem-pic-bg" style="background-image: url({{  MEDIA_URL  }}{{ request.session.use_img }});"></div>
        </div>
        <ul class="member-menu">
            <li>
                <a href="records.html">
                    <p class="yellow">0</p>
                    <p class="black">帐户余额 </p>
                </a>
            </li>
            <li>
                <a href="integral.html">
                    <p class="yellow">0</p>
                    <p class="black">积分 </p>
                </a>
            </li>
            <li>
                <a href="yhq.html">
                    <p class="yellow">0</p>
                    <p class="black">优惠劵 </p>
                </a>
            </li>
            <li>
                <a href="collect.html">
                    <p class="yellow">0</p>
                    <p class="black">我的收藏 </p>
                </a>
            </li>
        </ul>
    </div>
    <div class="user-list">
        <div class="u-list-main">
            <img src="{% static 'images/order-pic.png' %}" width="27"/>
            <span>我的购物订单</span>
            <a href="allorder.html">查看全部订单></a>
        </div>
        <ul class="user-nav">
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}">
                <p>待付款</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}">
                <p>待收货</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}">
                <p>待评价</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}">
                <p>退换货</p></a></li>
        </ul>
        <div class="u-list-main">
            <img src="{% static 'images/order-my.png' %}" width="27"/>
            <span>帐户与安全</span>
        </div>
        <ul class="user-nav">
            <li><a href="{% url '用户:个人资料' %}"> <img src="{% static 'images/1-icon4.png' %}">
                <p>个人资料</p></a></li>
            <li><a href="{% url '用户:收货地址首页' %}"> <img src="{% static 'images/1-icon5.png' %}">
                <p>收货地址</p></a></li>
            <li><a href="{% url '用户:安全设置页' %}"> <img src="{% static 'images/1-icon6.png' %}">
                <p>安全设置</p></a></li>
            <li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}">
                <p>我的钱包</p></a></li>
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav"
        style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
        <li>
            <div class="am-gallery-item">
                <a href="job.html" class="">
                    <img src="{% static 'images/m_03.png' %}"/>
                    <p>我要兼职</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="recommend.html" class="">
                    <img src="{% static 'images/m_04.png' %}"/>
                    <p>推荐有奖</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="myrecommend.html" class="">
                    <img src="{% static 'images/m_05.png' %}"/>
                    <p>我的推荐</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_06.png' %}"/>
                    <p>我的佣金</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/m_02.png' %}"/>
                    <p>我的红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="message.html" class="">
                    <img src="{% static 'images/m_07.png' %}"/>
                    <p>我的动态</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/m_08.png' %}"/>
                    <p>客服中心</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_09.png' %}"/>
                    <p>安全退出</p>
                </a>
            </div>
        </li>
    </ul>
    </div>
    <!--客服中心-->
    <div class="qd-box">
        <div class="popup-title">
            <span>客服中心</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
                <img src="{% static 'images/contactqq.png' %}" width="50"/>
                <p class="contactqq">联系QQ</p>
            </a>
            <a href="tel:0791-12345678">
                <img src="{% static 'images/contacttele.png' %}" width="50"/>
                <p class="contacttele">呼叫电话</p>
            </a>
        </div>
    </div>
    <!--客服中心-->
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:购物车页面' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url '用户:个人中心' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>


    <script type='text/javascript'>
        (function () {
            new PopUp_api({el: '.index-qd', html: '.qd-box'});
        })()
    </script>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>
    </body>

{% endblock %}

market/templates/user/saftystep.html
{% extends 'basetem/basetem_user.html' %}
{% load static %}

{% block title %}
安全设置页
{% endblock %}

{% block aaa %}
   安全设置
{% endblock %}

{% block content %}
	    <ul class="safty">
	    	<li>
	    		<a href="{% url '用户:重置密码' %}">
	    			<img src="{% static 'images/update.png' %}" width="40" />
	    			<i>修改登录密码</i>
	    			<span class="am-icon-angle-right"></span>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="payment.html">
	    			<img src="{% static 'images/moneysafty.png' %}" width="40" />
	    			<i>设置支付密码</i>
	    			<span class="am-icon-angle-right"></span>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="{% url '用户:重置手机号码' %}">
	    			<img src="{% static 'images/moneytele.png' %}" width="40" />
	    			<i>绑定手机号</i>
	    			<span class="am-icon-angle-right"></span>
	    			<i style="float: right; padding-right: 10px;">136****3128</i>
	    		</a>
	    		<p style="overflow: hidden;">若你的手机已修改或信用，请立即更换</p>
	    	</li>
	    </ul>
{% endblock %}